config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  root to: 'home#index'

  resources :flowers
  resources :carts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :flower
end

app/models/flower.rb
class Flower < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def username
    email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @carts = Cart.all
  end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_flower, only: [:show, :edit, :update, :destroy]

  def index
    @flowers = Flower.all
  end

  def new
    @flower = Flower.new
  end

  def edit
  end

  def show
  end

  def update
    if @flower.update(flower_params)
      redirect_to flowers_path, notice: "#{@flower.name}'s info is successfully updated"
    end
  end

  def create
    @flower = Flower.new(flower_params)
    if @flower.save
      redirect_to flowers_path, notice: "#{@flower.name} is successfully added"
    else
      render :new
    end
  end

  def destroy
    @flower.destroy
      redirect_to flowers_path, alert: "flower #{@flower.name} removed from the shop"
  end

  private

  def flower_params
    params.require(:flower).permit(:name, :qty, :price)
  end

  def set_flower
    @flower = Flower.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
  # def user_action(flower)
  #   if current_user&.admin
  #     link_to 'Edit', edit_flower_path(flower),
  #       class:"btn btn-sm btn-outline-info"
  #     link_to 'Delete', flower_path(flower),
  #       method: :delete,
  #       class:"btn btn-sm btn-outline-danger"
  #     link_to 'Add flower', new_flower_path,
  #       class:"btn btn-sm btn-outline-success"
  #   else
  #     link_to 'Buy now', cart_path(flower),
  #       class:"btn btn-sm btn-outline-primary"
  #   end
  # end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/carts/index.html.erb
<h1>Shopping cart</h1>

<table class="table table-hover table-bordered">
  <thead class="table table-secondary">
    <tr>
      <th>Flower name</th>
      <th>Quantity ordered</th>
      <th>Order total</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @carts.each do |flower| %>
      <tr>
        <td><%= flower.name %></td>
        <td><%= flower.qty %> pieces</td>
        <td>₱ <%= flower.price %></td>
        <td><%= link_to 'Checkout', carts_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Checkout', "#", class:"btn btn-outline-success" %><br><br>
<%= link_to 'Back', flowers_path, class:"btn btn-sm btn-outline-secondary" %>

app/views/carts/show.html.erb
<h1>Shopping cart</h1>

<table class="table table-hover table-bordered">
  <thead class="table table-secondary">
    <tr>
      <th>Flower name</th>
      <th>Quantity ordered</th>
      <th>Order total</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @carts.each do |flower| %>
      <tr>
        <td><%= @flower.name %></td>
        <td><%= @flower.qty %> pieces</td>
        <td>₱ <%= @flower.price %></td>
        <td><%= link_to 'Checkout', flowers_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', flowers_path %>

app/views/flowers/_form.html.erb
<div class="container">

<p>Fill out the form</p>
<%= form_for @flower do |f| %>
  <div class="field">
    Flower name <br />
    <%= f.text_field :name, required: true, autofocus: true, class:"form-control" %>
  </div> <br />

  <div class="field">
    No. of this flower available <br />
    <%= f.number_field :qty, min: 1, max: 1000000, required: true, class:"form-control" %>
  </div> <br />

  <div class="field">
    Flower price <br />
    <%= f.text_field :price, placeholder: "₱", required: true, class:"form-control" %>
  </div> <br />

  <div class="actions">
    <%= f.submit "Save & continue", class:"btn btn-sm btn-outline-success" %> 
    <%= link_to 'Cancel', flowers_path, class:"btn btn-sm btn-outline-secondary" %>
  </div> <br />
<% end %>

</div>

app/views/flowers/edit.html.erb
<h1>Edit</h1>

<%= render 'form', flower: @flower %>

app/views/flowers/index.html.erb
<h1>Flower Shop</h1>

<table class="table table-hover table-bordered">
  <thead class="table table-secondary">
    <tr>
      <th>Flower name</th>
      <th>Available quantity</th>
      <th>Flower price</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @flowers.each do |flower| %>
      <tr>
        <td><%= link_to flower.name, flower_path(flower) %></td>
        <td><%= flower.qty %> pieces</td>
        <td>₱ <%= flower.price %></td>
        <% if current_user&.admin %>
          <td><%= link_to 'Delete', flower_path(flower),
            method: :delete,
            data: {confirm:"Are you sure?"},
            class:"btn btn-sm btn-outline-danger" %>
          </td>
        <% else %>
          <td><%= link_to 'Add to cart', carts_path,
            class:"btn btn-sm btn-outline-success" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user&.admin %>
  <%= link_to 'Add flower', new_flower_path,
    class:"btn btn-sm btn-outline-success" %>
<% end %>

<%= link_to 'Home', root_path, class:"btn btn-sm btn-outline-secondary" %>

app/views/flowers/new.html.erb
<h1>Add new flower in the list</h1>

<%= render 'form' %>

app/views/flowers/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @flower.name %></h1>
  <p class="lead">Purity</p>
  <ul><li> White roses traditionally are often used at weddings. This is because they represent purity, making them a perfect option for marriage. They also represent youthfulness, innocence, young love, and loyalty.</li></ul>
  <hr class="my-4">
      <p>Available quantity: <strong><%= @flower.qty %></strong> pieces</p>
      <p>Flower price: ₱<strong><%= @flower.price %></strong></p>
  <p class="lead">
    <a>
      <% if current_user&.admin %>
        <%= link_to 'Edit', edit_flower_path(@flower),
          class:"btn btn-sm btn-outline-info" %>
      <% end %>
        <%= link_to 'Back', flowers_path,
          class:"btn btn-sm btn-outline-secondary" %>
    </a>
  </p>
</div>

app/views/home/index.html.erb
<h1>Homepage</h1>

<% if current_user&.admin %>
  <%= link_to "#{current_user.username}'s flower shop", flowers_path, class:"btn btn-sm btn-outline-primary" %>
<% else %>
  <%= link_to 'Shop flowers', flowers_path, class:"btn btn-sm btn-outline-primary" %>
<% end %>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice alert-info"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_user.html.erb
<% if user_signed_in? %>
  <%= current_user.username %>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete, class:"btn btn-sm btn-outline-dark" %> <br />
<% end %>

<% if current_user&.admin %>
  <%= "Seller View" %>
<% else %>
  <%= "Buyer View" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonshopCpmon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/alerts' %>
    <%= render 'layouts/user' %>

    <%= yield %>
  </body>
</html>